### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by ericgio** [yekrojam/api#6]
If validation fails when creating a user, the client receives the following error:
```
'E11000 duplicate key error index: yekrojam.users.$email_1 dup key: { : "test@test.com" }'
```
In general, I think the API should send user-friendly error messages that the client can simply display to the user.

**Comment by makinde** [comment]
Good timing. This just got swept into some of the testing I was doing. I can think of two big cases here.

1) When something just goes wrong and a general, helpful error message needs to come back.
2) When there's a validation issue with a specific part of the operation. I think it's good to get back a helpful error message, and I think it should now be sending that back. But it tries to be very specific, specifying the field where the error came from. If you want, you can parse that response and display the error by the specific field that created the issue. Lmk if that's helpful.

**Comment by ericgio** [comment]
I think the second case is the more important issue. The first case is basically a 500 error or something, in which case the client can just display its own generic error, eg: "Sorry, something went wrong. Please refresh the page and try again."

For 2, I agree with your assessment. There should be some kind of structured error that the client can parse and display in a user-friendly way.

**Comment by makinde** [comment]
Strange. What's the JSON for the user you're trying to create? If you set the api `DEBUG` env variable to `*`, you'll get the error spot out to you in the logs.

**Comment by ericgio** [comment]
> If you set the api DEBUG env variable to *, you'll get the error spot out to you in the logs.

Snap. I had `DEBUG=true` and was confused about why I wasn't seeing anything...

**Comment by ericgio** [comment]
Request body:
```js
{ name: 'test', email: 'test@tester.com' }
```

Error:
```
  api ValidationError: Validation failed
  api     at new ValidationError (/Users/ericgio/Projects/yekrojam/api/node_modules/mongoose/lib/error/validation.js:28:11)
  api     at /Users/ericgio/Projects/yekrojam/api/node_modules/mongoose-beautiful-unique-validation/index.js:159:31
  api     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```

**Comment by makinde** [comment]
I'm guessing based on where the error is coming from in the stack trace. There's already a user with the email `test@tester.com` in your DB. Not sure why the error is getting mangled. When I run master locally I get the following error back when trying to duplicate an email address.

```
{
    "message": "Validation failed",
    "name": "ValidationError",
    "errors": {
        "email": "Path `email` (sarah@exa2mple.com) is not unique."
    }
}
```

**Comment by makinde** [comment]
Oh, I completely missed that this discussion was on an existing issue. Let me do an `npm ci` and see if it breaks for me.

**Comment by makinde** [comment]
Interesting. And what you pasted above is all the comes out about the error? What's above/below that you pasted to me?

**Comment by ericgio** [comment]
Yes, that's all I'm seeing

**Comment by makinde** [comment]
The plot thickens. Is this on Heroku? Or your local dev? if the latter, you have mongodb installed locally? or hitting it on mLab or something?

**Comment by ericgio** [comment]
Locally, hitting mLab. Once the user is created, it appears I can update them. Just can't create for some reason.

**Comment by makinde** [comment]
Hmmm, not sure what's going on. Will be able to poke around more tomorrow. On the east coast, so about to go to bed. 

In the mean time, you might be able to log into mLab and rebuild the index. Also, one possibility is that a deleted document is somehow still in the index?

**Comment by ericgio** [comment]
Cool, thanks will check that out.

**Comment by ericgio** [comment]
Yup, that was it :) Had a leftover unique index for `urlSlug`. I deleted that and things seem to be working again. Sigh.... Thanks and good night!

**Comment by makinde** [comment]
Glad you found it. I'm a little surprised that having that index wouldn't allow docs to be created without the field.  But I think that just highlights my thin understanding of things :P

More broadly, mongodb/mongoose recommends explicitly running the commands to create and remove indices on prod databases. Instead we continue to rely on mongoose to auto-make them based on the schema. Just seems like so much effort/things to keep track of, and MK did it the automatic way and never ran into problems. Probably a lurking issue to track.

**Comment by makinde** [comment]
Should be good to go after #29 landed

**Comment by ericgio** [comment]
Related to my issue above, it looks like we're not handling validation errors related to unique indexes yet. I can look into the problem, but let's keep this issue open in the meantime.

**Comment by makinde** [comment]
Oh I see. I think the issue with the (user, org) index is that the error isn't on any single field. The user is valid on its own. The org is valid on its own.  But the combination of them is not valid. What might the error object be look like to reflect that underlying issue?

**Comment by ericgio** [comment]
Fixed it with a different validation lib, see #36

**Comment by ericgio** [comment]
My master is up to date. I suspect it's actually an issue with the indexes in my DB. I initially created some documents directly in the DB and not through mongoose, and I wonder if that's messing something up.
